// THINGS TO DO
  // TEMPERATURE LOOP
  // AMBIENT TEMPERATURE
  // TESTING GCODE DATABASE FOR ERRORS
  // TEST DIRECTIONAL PIN OUTPUTS OF MOTORS
  // FURTHER DEFINE LOOPS AT GREATER DEGREES BY TRYING TO FIND COMMON RATIOS
  // ADD MORE M COMMAND IMPLEMENTATION
  // FINISH ALL GCODE COMMANDS IMPLEMENTATION
  // VERIFY SIMPLIFY IS HAPPY WITH MACHINE CONTROLLER SOFTWARE
  // FIX TO ONLY SAY "OK" IF THERE IS 8 OR LESS COMMANDS IN CACHE (EASY)
  // ADD REAL TIME CLOCK
  // ADD TOLERANCE
  // FIX TEMP SENSING PROBLEM
  // YAY